#!/usr/bin/env sh


waybar -b 1 -c ~/Lu-dots/Bedrock-hypr/Components/waybar/config_hyprland_1 -s ~/Lu-dots/Bedrock-hypr/Components/waybar/style_hyprland_1.css &
waybar -b 2 -c ~/Lu-dots/Bedrock-hypr/Components/waybar/config_hyprland_2 -s ~/Lu-dots/Bedrock-hypr/Components/waybar/style_hyprland_2.css
