#!/usr/bin/env sh

sudo pacman -S pacman-contrib base-devel --noconfirm


git clone https://aur.archlinux.org/hyprland-bin.git
cd hyprland-bin
makepkg -si --noconfirm

git clone https://aur.archlinux.org/waybar-hyprland-git.git
cd waybar-hyprland-git
makepkg -si --noconfirm

git clone https://aur.archlinux.org/rofi-lbonn-wayland-git.git
cd rofi-lbonn-wayland-git
makepkg -si --noconfirm

git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si --noconfirm


rm -rf hyprland-bin/
rm -rf waybar-hyprland-git/
rm -rf rofi-lbonn-wayland-git/
rm -rf yay-bin/