#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/Lu-dots/hypr/Components/Rofi/"
STYLE="default"
RASI="$DIR/Rasi/runner.rasi"

# Run
rofi \
    -show run \
	-theme ${RASI}
