#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/Lu-dots/Bedrock-hypr/Components/Rofi/"
STYLE="default"
RASI="$DIR/Rasi/askpass.rasi"

# rofi text dialog to get password
rofi -dmenu \
     -password \
     -i \
     -p "Root" \
     -theme ${RASI}
