#!/usr/bin/env sh


waybar -b 1 -c /home/luiza/.config/waybar/hyprland/config_hyprland_1 -s /home/luiza/.config/waybar/hyprland/style_hyprland_1.css
waybar -b 2 -c /home/luiza/.config/waybar/hyprland/config_hyprland_2 -s /home/luiza/.config/waybar/hyprland/style_hyprland_2.css
    