#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/Lu-dots/pink-alt/Components/Rofi/"
STYLE="default"
RASI="$DIR/Rasi/launcher.rasi"


# Run
rofi \
    -show drun \
	-theme ${RASI}
